[package]
name = "extractors"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.0.0-beta.10"
actix-web-httpauth = "0.8.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures-util = "0.3"
actix-multipart = "0.7.2"
derive_more = "0.99.17"